site_name: Notifs Documentation
site_url: https://dootss.github.io/notifs
repo_url: https://github.com/dootss/notifs
site_description: A library for easy terminal notifications.
nav:
  - Home: index.md
  - Installation: installation.md
  - Usage: usage.ipynb
  - API Reference: api_reference.ipynb
  - Examples: examples.ipynb

theme:
  name: material
  palette:
    scheme: slate    # Use a dark theme by default
    primary: indigo  # Choose the primary color
    accent: indigo   # Choose the accent color
  features:
    - navigation.tabs    # Enable navigation tabs
    - navigation.instant # Enable instant loading
# syntax highlighting!!!
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
plugins:
  - mkdocs-jupyter:
      execute: true
extra_css:
  - assets/css/custom.css

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/dootss