site_name: Notifs Documentation
nav:
  - Home: index.md
  - Installation: installation.md
  - Usage: usage.md
  - API Reference: api_reference.md
theme:
  name: material
  palette:
    scheme: slate    # Use a dark theme by default
    primary: indigo  # Choose the primary color
    accent: indigo   # Choose the accent color
  features:
    - navigation.tabs    # Enable navigation tabs
    - navigation.instant # Enable instant loading
# syntax highlighting!!!
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
